{% set name = "smbus2" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smbus2-{{ version }}.tar.gz
  sha256: 36f2288a8e1a363cb7a7b2244ec98d880eb5a728a2494ac9c71e9de7bf6a803a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - smbus2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kplindegaard/smbus2
  summary: smbus2 is a drop-in replacement for smbus-cffi/smbus-python in pure Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
